name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *" # cada 12 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: endbug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update GitHub stats"