name: Generate Snake Animation

on:
  # Ejecuta el workflow cada 6 horas
  schedule:
    - cron: "0 */6 * * *" 
  # Permite ejecutarlo manualmente desde la pestaña "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: baa4ts # Tu nombre de usuario de GitHub
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # La rama donde se guardará el SVG/GIF generado
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}